### ISSUE TITLE
Extra items in requirements

### ISSUE THREAD

**Issue by askpatrickw** [jepler/Jepler_CircuitPython_udecimal#5]
circup is very unhappy with udecimal. :-)

Should the requirements.txt include all these things?
Seems like other libraries don't include things like black and sphinx, etc... or they use a dev requirements.

Found device at /Volumes/CIRCUITPY, running CircuitPython 7.0.0-alpha.3-433-g5a4a80336.
Searching for dependencies for: ['jepler_udecimal']
WARNING:
	astroid is not a known CircuitPython library.
WARNING:
	black is not a known CircuitPython library.
WARNING:
	isort is not a known CircuitPython library.
WARNING:
	pre-commit is not a known CircuitPython library.
WARNING:
	recommonmark is not a known CircuitPython library.
WARNING:
	sphinx is not a known CircuitPython library.
WARNING:
	sphinx-autoapi is not a known CircuitPython library.
WARNING:
	sphinxcontrib-svg2pdfconverter is not a known CircuitPython library.
WARNING:
	sphinx-rtd-theme is not a known CircuitPython library.
WARNING:
	setuptools is not a known CircuitPython library.
WARNING:
	wheel is not a known CircuitPython library.
WARNING:
	twine is not a known CircuitPython library.
WARNING:
	readme_renderer is not a known CircuitPython library.
WARNING:
	testresources is not a known CircuitPython library.
WARNING:
	circuitpython_build_tools is not a known CircuitPython library.
Ready to install: ['jepler_udecimal']

**Comment by jepler** [comment]
```
$ ./.env/bin/circup install jepler_udecimal
Found device at /media/jepler/CIRCUITPY, running CircuitPython 7.0.0-alpha.6.
Searching for dependencies for: ['jepler_udecimal']
Ready to install: ['jepler_udecimal']

Installed 'jepler_udecimal'.
``` 
seems fixed now, let me know if you see different.
