### ISSUE TITLE
utrig arcsin(x) not working for domain of |x| <= 1

### ISSUE THREAD

**Issue by CedarGroveStudios** [jepler/Jepler_CircuitPython_udecimal#7]
`utrig` line 185:

The arctan method for determining `arcsin(x)` only works for values in the domain of |x| < 1 rather than |x| <= 1. The method throws a `DivisionByZero` error for x = 1 or x = -1.

**Comment by jepler** [comment]
I'd be happy to accept a patch that special cases these two values. Add a test for bonus points.

**Comment by CedarGroveStudios** [comment]
I'm not fully confident in my understanding of using arctan to derive arccos and arcsin, but could take a stab at simply substituting 1/2*pi or 3/2*pi for the domain boundary conditions.
